# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  fork:  
    - uses: dev-drprasad/delete-older-releases@v1.1.0
      with:
      repo: "AhmedSShadad/AutoApp" 
      keep_latest: 3
      delete_tag_pattern: "v.1"
      env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
