

name: Dart  

on:
  push:
    tags:
    - 'v*'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          
      - name: Install dependencies
        run: flutter pub get
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/iphoneos/app.ipa"
          tag: v1.1.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

        
